Repository knative-extensions/eventing-integrations, pull requests merged in 2024-11, with the labels that each got.

#35 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#37 [main] Update community files
  OWNERS_ALIASES
Labels: skip-review, size/S

#38 Remove the "connector.event" prefix in favor of "eventing"
  README.adoc
  aws-ddb-streams-source/src/main/resources/application.properties
  aws-ddb-streams-source/src/test/java/dev/knative/eventing/connector/AwsDdbStreamsSourceTest.java
  aws-s3-sink/src/test/java/dev/knative/eventing/connector/AwsS3SinkTest.java
  aws-s3-source/src/main/resources/application.properties
  aws-s3-source/src/test/java/dev/knative/eventing/connector/AwsS3SourceTest.java
  aws-s3-source/src/test/java/dev/knative/eventing/connector/ssl/AwsS3SourceSSLTest.java
  aws-sqs-sink/src/test/java/dev/knative/eventing/connector/AwsSqsSinkTest.java
  aws-sqs-source/src/main/resources/application.properties
  aws-sqs-source/src/test/java/dev/knative/eventing/connector/AwsSqsSourceTest.java
  log-sink/src/test/java/dev/knative/eventing/connector/LogSinkTest.java
  timer-source/src/main/resources/application.properties
  timer-source/src/test/java/dev/knative/eventing/connector/TimerSourceTest.java
  timer-source/src/test/java/dev/knative/eventing/connector/ssl/TimerSourceSSLTest.java
  tools/archetype-source/src/main/resources/archetype-resources/src/main/resources/application.properties
Labels: lgtm, approved, size/M

#41 Add AWS SNS Sink tests
  aws-sns-sink/pom.xml
  aws-sns-sink/src/test/java/dev/knative/eventing/connector/AwsSnsSinkTest.java
  aws-sns-sink/src/test/java/dev/knative/eventing/connector/LocalstackTestResource.java
  aws-sns-sink/src/test/resources/application.properties
  tools/archetype-sink/src/main/resources/archetype-resources/pom.xml
  tools/archetype-source/src/main/resources/archetype-resources/pom.xml
Labels: lgtm, size/L, approved

#42 Ignore warnings during test execution related to Citrus split packages
  aws-ddb-streams-source/src/test/resources/application.properties
  aws-s3-sink/src/test/resources/application.properties
  aws-s3-source/src/test/resources/application.properties
  aws-sqs-sink/src/test/resources/application.properties
  aws-sqs-source/src/test/resources/application.properties
  log-sink/src/test/resources/application.properties
  timer-source/src/test/resources/application.properties
Labels: size/XS, lgtm, approved
