Repository knative-extensions/eventing-integrations, pull requests merged in 2024-12, with the labels that each got.

#45 Add initial support to produce images in ConfigMap as release artifact
  hack/release.sh
Labels: lgtm, approved, size/M

#47 Update to Quarkus 3.17.0 and Camel 4.9.0
  aws-ddb-streams-source/pom.xml
  aws-s3-sink/pom.xml
  aws-s3-source/pom.xml
  aws-sns-sink/pom.xml
  aws-sqs-sink/pom.xml
  aws-sqs-source/pom.xml
  log-sink/pom.xml
  pom.xml
  timer-source/pom.xml
  tools/archetype-sink/src/main/resources/archetype-resources/pom.xml
  tools/archetype-source/src/main/resources/archetype-resources/pom.xml
  tools/maven-plugin/src/main/java/dev/knative/eventing/connector/maven/plugin/GenerateConnectorSpecMojo.java
Labels: lgtm, approved, size/M

#49 Fix generated ConfigMap indentation
  hack/release.sh
Labels: lgtm, approved, size/S

#50 fix(#31): Enable OIDC support on integration sources
  README.adoc
  aws-ddb-streams-source/pom.xml
  aws-ddb-streams-source/src/main/java/dev/knative/eventing/SourceOptions.java
  aws-s3-source/pom.xml
  aws-s3-source/src/main/java/dev/knative/eventing/SourceOptions.java
  aws-sqs-source/pom.xml
  aws-sqs-source/src/main/java/dev/knative/eventing/SourceOptions.java
  common/pom.xml
  common/utils/pom.xml
  common/utils/src/main/java/dev/knative/eventing/source/KnativeHttpClientOptions.java
  pom.xml
  timer-source/pom.xml
  timer-source/src/main/java/dev/knative/eventing/SourceOptions.java
  timer-source/src/test/java/dev/knative/eventing/connector/oidc/TimerSourceOIDCTest.java
  timer-source/src/test/resources/oidc/token
  tools/archetype-source/src/main/resources/archetype-resources/pom.xml
  tools/archetype-source/src/main/resources/archetype-resources/src/main/java/dev/knative/eventing/SourceOptions.java
Labels: lgtm, approved, size/XL

#54 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review
