Repository knative-extensions/eventing-integrations, pull requests merged in 2024-10, with the labels that each got.

#1 Adding proper approvers
  OWNERS
Labels: size/XS, lgtm

#2 [main] Update community files
  OWNERS_ALIASES
Labels: skip-review, size/L

#4 Fix missing Maven wrapper
  .mvn/wrapper/maven-wrapper.jar
  .mvn/wrapper/maven-wrapper.properties
Labels: lgtm, approved, size/S

#5 Adding s3 bucket sink
  aws-s3-sink/README.adoc
  aws-s3-sink/pom.xml
  aws-s3-sink/properties.adoc
  aws-s3-sink/src/main/docker/Dockerfile.jvm
  aws-s3-sink/src/main/docker/Dockerfile.legacy-jar
  aws-s3-sink/src/main/docker/Dockerfile.native
  aws-s3-sink/src/main/docker/Dockerfile.native-micro
  aws-s3-sink/src/main/kubernetes/kubernetes.yml
  aws-s3-sink/src/main/resources/META-INF/LICENSE.txt
  aws-s3-sink/src/main/resources/META-INF/NOTICE.txt
  aws-s3-sink/src/main/resources/application.properties
  aws-s3-sink/src/main/resources/camel/kn-connector-sink.yaml
  aws-s3-sink/src/main/resources/knative.json
  pom.xml
Labels: lgtm, approved, size/XL

#8 Adding s3 sqs sink
  aws-sqs-sink/README.adoc
  aws-sqs-sink/pom.xml
  aws-sqs-sink/properties.adoc
  aws-sqs-sink/src/main/docker/Dockerfile.jvm
  aws-sqs-sink/src/main/docker/Dockerfile.legacy-jar
  aws-sqs-sink/src/main/docker/Dockerfile.native
  aws-sqs-sink/src/main/docker/Dockerfile.native-micro
  aws-sqs-sink/src/main/kubernetes/kubernetes.yml
  aws-sqs-sink/src/main/resources/META-INF/LICENSE.txt
  aws-sqs-sink/src/main/resources/META-INF/NOTICE.txt
  aws-sqs-sink/src/main/resources/application.properties
  aws-sqs-sink/src/main/resources/camel/kn-connector-sink.yaml
  aws-sqs-sink/src/main/resources/knative.json
  pom.xml
Labels: lgtm, approved, size/XL

#9 Regen docs
  aws-s3-sink/pom.xml
  aws-s3-sink/properties.adoc
  aws-s3-sink/properties.yaml
  aws-sqs-sink/pom.xml
  aws-sqs-sink/properties.adoc
  aws-sqs-sink/properties.yaml
Labels: lgtm, size/L, approved

#10 Update data plane to serve webserver on context, not - as this is uncommon in Knative lands
  README.adoc
  aws-s3-sink/README.adoc
  aws-s3-sink/src/main/kubernetes/kubernetes.yml
  aws-s3-sink/src/main/resources/knative.json
  aws-sqs-sink/README.adoc
  aws-sqs-sink/src/main/kubernetes/kubernetes.yml
  aws-sqs-sink/src/main/resources/knative.json
  log-sink/README.adoc
  log-sink/src/main/kubernetes/kubernetes.yml
  log-sink/src/main/resources/knative.json
  log-sink/src/test/java/dev/knative/eventing/connector/LogSinkTest.java
  tools/archetype-sink/src/main/resources/archetype-resources/README.adoc
  tools/archetype-sink/src/main/resources/archetype-resources/src/main/kubernetes/kubernetes.yml
  tools/archetype-sink/src/main/resources/archetype-resources/src/main/resources/knative.json
Labels: lgtm, approved, size/S

#13 adding required setting to properties file
  aws-s3-sink/src/main/resources/application.properties
Labels: size/XS, lgtm, approved

#15 adding required setting to properties file
  aws-sqs-sink/src/main/resources/application.properties
Labels: size/XS, lgtm, approved

#16 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#17 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#19 Add AWS sink tests
  aws-s3-sink/pom.xml
  aws-s3-sink/src/test/java/dev/knative/eventing/connector/AwsS3SinkTest.java
  aws-s3-sink/src/test/java/dev/knative/eventing/connector/LocalstackTestResource.java
  aws-sqs-sink/pom.xml
  aws-sqs-sink/src/test/java/dev/knative/eventing/connector/AwsSqsSinkTest.java
  aws-sqs-sink/src/test/java/dev/knative/eventing/connector/LocalstackTestResource.java
Labels: lgtm, size/L, approved

#18 Add image build config and release script
  go.mod
  go.sum
  hack/release.sh
  hack/tools.go
  pom.xml
Labels: lgtm, approved, size/M

#20 Remove kn- prefix from module names
  aws-ddb-streams-source/pom.xml
  aws-s3-sink/pom.xml
  aws-s3-source/pom.xml
  aws-sqs-sink/pom.xml
  aws-sqs-source/pom.xml
  log-sink/pom.xml
  pom.xml
  timer-source/pom.xml
  tools/archetype-sink/pom.xml
  tools/archetype-sink/src/main/resources/archetype-resources/pom.xml
  tools/archetype-source/pom.xml
  tools/archetype-source/src/main/resources/archetype-resources/pom.xml
  tools/maven-plugin/pom.xml
  tools/pom.xml
Labels: lgtm, approved, size/M

#23 Removing connector image prefix
  aws-ddb-streams-source/pom.xml
  log-sink/pom.xml
Labels: size/XS, lgtm, approved

#24 Add placeholder presubmit test script
  test/presubmit-tests.sh
  test/presubmit-tests.sh.tmpl
Labels: lgtm, approved, size/S

#26 Add latest tag build configuration
  pom.xml
Labels: size/XS, lgtm, approved

#30 Remove kn-connector prefix in sources
  README.adoc
  aws-ddb-streams-source/README.adoc
  aws-ddb-streams-source/src/main/kubernetes/kubernetes.yml
  aws-ddb-streams-source/src/main/resources/application.properties
  aws-ddb-streams-source/src/main/resources/camel/source.yaml
  aws-s3-sink/README.adoc
  aws-s3-sink/src/main/kubernetes/kubernetes.yml
  aws-s3-sink/src/main/resources/application.properties
  aws-s3-sink/src/main/resources/camel/sink.yaml
  aws-s3-source/README.adoc
  aws-s3-source/src/main/kubernetes/kubernetes.yml
  aws-s3-source/src/main/resources/application.properties
  aws-s3-source/src/main/resources/camel/source.yaml
  aws-sqs-sink/README.adoc
  aws-sqs-sink/src/main/kubernetes/kubernetes.yml
  aws-sqs-sink/src/main/resources/application.properties
  aws-sqs-sink/src/main/resources/camel/sink.yaml
  aws-sqs-source/README.adoc
  aws-sqs-source/src/main/kubernetes/kubernetes.yml
  aws-sqs-source/src/main/resources/application.properties
  aws-sqs-source/src/main/resources/camel/source.yaml
  log-sink/README.adoc
  log-sink/src/main/kubernetes/kubernetes.yml
  log-sink/src/main/resources/application.properties
  log-sink/src/main/resources/camel/sink.yaml
  timer-source/README.adoc
  timer-source/src/main/kubernetes/kubernetes.yml
  timer-source/src/main/resources/application.properties
  timer-source/src/main/resources/camel/source.yaml
  tools/archetype-sink/src/main/resources-filtered/META-INF/maven/archetype-metadata.xml
  tools/archetype-sink/src/main/resources/archetype-resources/README.adoc
  tools/archetype-sink/src/main/resources/archetype-resources/src/main/kubernetes/kubernetes.yml
  tools/archetype-sink/src/main/resources/archetype-resources/src/main/resources/application.properties
  tools/archetype-sink/src/main/resources/archetype-resources/src/main/resources/camel/sink.yaml
  tools/archetype-source/src/main/resources-filtered/META-INF/maven/archetype-metadata.xml
  tools/archetype-source/src/main/resources/archetype-resources/README.adoc
  tools/archetype-source/src/main/resources/archetype-resources/src/main/kubernetes/kubernetes.yml
  tools/archetype-source/src/main/resources/archetype-resources/src/main/resources/application.properties
  tools/archetype-source/src/main/resources/archetype-resources/src/main/resources/camel/source.yaml
Labels: lgtm, size/L, approved

#33 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#34 fix(#32): Support multiple CA certs
  README.adoc
  common/utils/src/main/java/dev/knative/eventing/source/KnativeHttpClientOptions.java
Labels: lgtm, size/L, approved
