Repository knative-extensions/eventing-integrations, pull requests merged in 2025-04, with the labels that each got.

#76 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#80 Upgrade knative/hack package
  go.mod
  go.sum
Labels: size/XS, lgtm, approved

#82 Fix release script to respect KO_DOCKER_REPO
  hack/release.sh
Labels: size/XS, lgtm, approved

#86 [main] Update community files
  OWNERS_ALIASES
Labels: skip-review, size/S
