Repository knative-extensions/eventing-integrations, pull requests merged in 2025-02, with the labels that each got.

#64 jsonata: allow transforming or discarding responses from K_SINK endpoint
  transform-jsonata/README.md
  transform-jsonata/examples/example-token.txt
  transform-jsonata/jsonata.js
  transform-jsonata/package.json
Labels: lgtm, size/L, approved

#65 Build and release transform-jsonata
  hack/build.sh
  hack/common.sh
  hack/release.sh
  test/presubmit-tests.sh
  transform-jsonata/.dockerignore
  transform-jsonata/Dockerfile
Labels: lgtm, approved, size/M

#66 Fix separator for image SHA in integrations images refs
  hack/release.sh
Labels: size/XS, lgtm, approved

#68 Jsonata: Support tracing
  transform-jsonata/README.md
  transform-jsonata/jsonata.js
  transform-jsonata/package.json
  transform-jsonata/pnpm-lock.yaml
Labels: lgtm, size/L, approved

#67 Add build tests
  hack/build.sh
  hack/common.sh
  hack/release.sh
  test/presubmit-tests.sh
  transform-jsonata/Dockerfile
  transform-jsonata/README.md
  transform-jsonata/jsonata.js
  transform-jsonata/package-lock.json
  transform-jsonata/package.json
  transform-jsonata/pnpm-lock.yaml
Labels: lgtm, size/XXL, approved

#69 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#70 Exec build-tests only in presubmit-tests.sh
  test/presubmit-tests.sh
Labels: size/XS, lgtm, approved
