Repository knative-extensions/eventing-integrations, pull requests merged in 2025-01, with the labels that each got.

#55 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#56 Update to Citrus 4.5.1
  aws-ddb-streams-source/src/test/resources/citrus-application.properties
  aws-s3-sink/src/test/resources/citrus-application.properties
  aws-s3-source/src/test/resources/citrus-application.properties
  aws-sns-sink/src/test/resources/citrus-application.properties
  aws-sqs-sink/src/test/resources/citrus-application.properties
  aws-sqs-source/src/test/resources/citrus-application.properties
  log-sink/src/test/resources/citrus-application.properties
  pom.xml
  timer-source/src/test/resources/citrus-application.properties
Labels: lgtm, approved, size/M

#59 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#57 fix(#14): Remove obsolete empty default property values
  aws-ddb-streams-source/src/main/resources/application.properties
  aws-s3-sink/src/main/resources/application.properties
  aws-s3-source/src/main/resources/application.properties
  aws-sns-sink/src/main/resources/application.properties
  aws-sqs-sink/src/main/resources/application.properties
  aws-sqs-source/src/main/resources/application.properties
Labels: lgtm, approved, size/S

#58 Remove obsolete camel-quarkus-knative-producer dependency
  aws-ddb-streams-source/pom.xml
  aws-s3-sink/pom.xml
  aws-s3-source/pom.xml
  aws-sns-sink/pom.xml
  aws-sqs-sink/pom.xml
  aws-sqs-source/pom.xml
  log-sink/pom.xml
  timer-source/pom.xml
  tools/archetype-sink/src/main/resources/archetype-resources/pom.xml
  tools/archetype-source/src/main/resources/archetype-resources/pom.xml
Labels: lgtm, approved, size/M

#60 [main] Update community files
  OWNERS_ALIASES
Labels: skip-review, size/S

#61 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review
