Repository knative-extensions/eventing-integrations, pull requests merged in 2025-03, with the labels that each got.

#73 Jsonata: Support creating TLS server
  transform-jsonata/.dockerignore
  transform-jsonata/README.md
  transform-jsonata/jsonata.js
  transform-jsonata/package-lock.json
  transform-jsonata/package.json
  transform-jsonata/ssl/server.crt
  transform-jsonata/ssl/server.key
Labels: lgtm, size/L, approved

#74 fix(#7): Update to Java 21
  .github/workflows/build.yml
  aws-ddb-streams-source/pom.xml
  aws-ddb-streams-source/src/main/docker/Dockerfile.jvm
  aws-ddb-streams-source/src/main/docker/Dockerfile.legacy-jar
  aws-ddb-streams-source/src/main/docker/Dockerfile.native
  aws-ddb-streams-source/src/main/docker/Dockerfile.native-micro
  aws-s3-sink/pom.xml
  aws-s3-sink/src/main/docker/Dockerfile.jvm
  aws-s3-sink/src/main/docker/Dockerfile.legacy-jar
  aws-s3-sink/src/main/docker/Dockerfile.native
  aws-s3-sink/src/main/docker/Dockerfile.native-micro
  aws-s3-source/pom.xml
  aws-s3-source/src/main/docker/Dockerfile.jvm
  aws-s3-source/src/main/docker/Dockerfile.legacy-jar
  aws-s3-source/src/main/docker/Dockerfile.native
  aws-s3-source/src/main/docker/Dockerfile.native-micro
  aws-sns-sink/pom.xml
  aws-sns-sink/src/main/docker/Dockerfile.jvm
  aws-sns-sink/src/main/docker/Dockerfile.legacy-jar
  aws-sns-sink/src/main/docker/Dockerfile.native
  aws-sns-sink/src/main/docker/Dockerfile.native-micro
  aws-sqs-sink/pom.xml
  aws-sqs-sink/src/main/docker/Dockerfile.jvm
  aws-sqs-sink/src/main/docker/Dockerfile.legacy-jar
  aws-sqs-sink/src/main/docker/Dockerfile.native
  aws-sqs-sink/src/main/docker/Dockerfile.native-micro
  aws-sqs-source/pom.xml
  aws-sqs-source/src/main/docker/Dockerfile.jvm
  aws-sqs-source/src/main/docker/Dockerfile.legacy-jar
  aws-sqs-source/src/main/docker/Dockerfile.native
  aws-sqs-source/src/main/docker/Dockerfile.native-micro
  log-sink/pom.xml
  log-sink/src/main/docker/Dockerfile.jvm
  log-sink/src/main/docker/Dockerfile.legacy-jar
  log-sink/src/main/docker/Dockerfile.native
  log-sink/src/main/docker/Dockerfile.native-micro
  pom.xml
  timer-source/pom.xml
  timer-source/src/main/docker/Dockerfile.jvm
  timer-source/src/main/docker/Dockerfile.legacy-jar
  timer-source/src/main/docker/Dockerfile.native
  timer-source/src/main/docker/Dockerfile.native-micro
  tools/archetype-sink/src/main/resources/archetype-resources/src/main/docker/Dockerfile.jvm
  tools/archetype-sink/src/main/resources/archetype-resources/src/main/docker/Dockerfile.legacy-jar
  tools/archetype-sink/src/main/resources/archetype-resources/src/main/docker/Dockerfile.native
  tools/archetype-sink/src/main/resources/archetype-resources/src/main/docker/Dockerfile.native-micro
  tools/archetype-source/src/main/resources/archetype-resources/pom.xml
  tools/archetype-source/src/main/resources/archetype-resources/src/main/docker/Dockerfile.jvm
  tools/archetype-source/src/main/resources/archetype-resources/src/main/docker/Dockerfile.legacy-jar
  tools/archetype-source/src/main/resources/archetype-resources/src/main/docker/Dockerfile.native
  tools/archetype-source/src/main/resources/archetype-resources/src/main/docker/Dockerfile.native-micro
Labels: lgtm, size/XXL, approved

#75 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review
